= IDEAS

== The combat system should be interesting
The combat system should be interesting for all types of characters, but not too cumbersom to take too much time to use.

=== Magic
* The caster should be able to cast spells at various levels of potency. e.g. chose the precentage or power-level for a spell when binding to a quick slot. Ammount of flexibility could be affected by a "mana-control" proficiency skill.
* Some traits/skills should affect mana points, magick potency, etc.
* stealth could play a part.
* (? could make things over-complicated) charged trinkets could be used to power-up or even cast some spells.

=== Melee
* Strength skill could affect damage, wepon skill should reduce fatigue needed for attacks, dexterity should affect to-hit ratios.
* If weilding a weapon with requirements for another proficiency, a fighter skilled enough in a different proficiency should still get some bonus compared to non-fighters i.e. some skills should default to others at a penalty.
* Possible to enchant the weapon temporarily via magic or potion/salve.
* stealth could play some part.

=== Ranged
* Strength should affect range, proficiency should affect accuracy and fatigue, perception should (?)conciderably affect accuracy.
* stealth could play a big part.
* special projectiles (e.g. poison, enchanted arrows, etc)
* weapon could be enchanted and charged to enchant it's on shot for a limited ammount shots/time.

=== All
* Potions, charged trinkets, etc to temporarily enhance ability, etc.

== Non-combat Possibilities of Magic Users
Interdimensional storage can lessen or even eliminate the need of pack animals.
Interdimensional travel spells can save a member from a deadly blow or could be used to gain passage to warded areas.
Personal dimension / arcane sanctuary can serve as a safe spot for resting, maybe even training/learning/research at higher levels.

== General Gameplay

=== Aging
The party will definitely age - this would lead to some immersive elements having more sense and impact e.g. training, getting incarcerated, time-passage difference between different dimensions (e.g. mages could use magical dimensions to learn/train a lot and not get much older), seeking for a way to stave-off death or get younger is a nice questing possibility, etc.

== Randomly Generated Content

=== Random generated levels
Could be a good way to level-up and/or find some treasure.

Could be some levels or quests e.g. go find/kill something beneath/close-to this place that causes this place inconvenience/greed/danger.
Other planes e.g. Astral, Arcane plane accessible through some long-forgotten magical door or a higher level spell.

== Misc/Unsorted
* magical portals
* dragons
* ancient ruins/castles/dungons
* magical passage ways to other dimensions
* legendary artefacts (some could be awesome equipment)
* named artefacts especially legendary, unique, rare stuff (i.e. LOTR glamdring, sting, ancient mythril armor could have gained a name as well)
