= IDEAS

== The combat system should be interesting
The combat system should be interesting for all types of characters, but not too cumbersom to take too much time to use.

=== Magic
* The caster should be able to cast spells at various levels of potency. e.g. chose the precentage or power-level for a spell when binding to a quick slot. Ammount of flexibility could be affected by a "mana-control" proficiency skill.
* Some traits/skills should affect mana points, magick potency, etc.
* stealth could play a part.
* (? could make things over-complicated) charged trinkets could be used to power-up or even cast some spells.

=== Melee
* Strength skill could affect damage, wepon skill should reduce fatigue needed for attacks, dexterity should affect to-hit ratios.
* If weilding a weapon with requirements for another proficiency, a fighter skilled enough in a different proficiency should still get some bonus compared to non-fighters i.e. some skills should default to others at a penalty.
* Possible to enchant the weapon temporarily via magic or potion/salve.
* stealth could play some part.

=== Ranged
* Strength should affect range, proficiency should affect accuracy and fatigue, perception should (?)conciderably affect accuracy.
* stealth could play a big part.
* special projectiles (e.g. poison, enchanted arrows, etc)
* weapon could be enchanted and charged to enchant it's on shot for a limited ammount shots/time.

=== All
* Potions, charged trinkets, etc to temporarily enhance ability, etc.

== Non-combat Possibilities of Magic Users
How to balance it in regards to other classes?

Magic levels for below comparisons 1 = novice 10 = legendary master

=== Interdimensional Box
summary::
Summon a box to store some items. The box dissapears back to it's origin dimension when the spell ends, and retains the items stored the next time it is summoned.

usage notes::
Quite useful to reduce ones encumberance as one does not need to physically carry stored items around, and said items are accessible any time the box is summoned.
Not useful to store items that might become needed immediately e.g. weapons. Because the spell taks some time to cast and uses energy that could otherwise be used for combat spells. A mage of extraordinary skill could mostly overcome these limitations though.

* LVL around 5
* energy use - casting:moderate maintaining:moderate(about 10min max initially for average human)
* casting time - a few minutes

=== Interdimensional Room
summary::
The caster enters a room outside normal space and time. Here he can has considerable space for storage and other things because nothing changes here between visits. Time passes differently in this dimension, thus the caster can do most mental things here e.g. studying, but no physical or magical effects on the body will progress or take effect if acquired in this dimension - this means that time will not heal or kill, and consuming any mundane or magical substances or casting spells is of no use here.
Regardless of how much time one spends here, he returns to the parent dimension as if no time had passed at all - less magically adept wil not even notice that anything happened.
It does take some energy to remain in the room for a considerable ammount of time, so spending more than a few days in this place is reserved for creatures that have absurd ammounts of magical power.

usage notes::
Mages who use this spell, usualy use the place as a store room and a refuge for the mind.

* LVL 7 or 8
* energy use - casting:moderate maintaining:moderate(about 1h max initially for average human)
* casting time - a few minutes

=== Interdimensional Mansion
(TODO) summary::
Some constraints of the Interdimensional Room lifted, and the place is larger. The Interdimensional Room can be accessed from here at no additional cost - it is a part of this place.

* LVL 10
* energy use casting:moderate maintaining:low (a few days max initially for average human)
* casting time - about an hour
